### ISSUE TITLE
Änderung VN in UN

### ISSUE THREAD

**Issue by arnese** [emtiu/GutachtenWissDienstBT#4]
Dankeschön für die Liste!
Die Änderung von VN in UN würde ich rückgängig machen - Die Gutachten sollten auch mit ihrem Originaltitel gefunden werden. Wenn der Bundestag das so benutzt, ist das halt so, denke ich.

**Comment by emtiu** [comment]
Ja, ich denke da hast Du Recht. Ich werde das mal mit der Original-Liste abgleichen und wieder zurück ändern, es geht auch nur um etwa ein Dutzend Gutachten.
